Repository bellshade/Assembly, pull requests merged in 2022-10, with the labels that each got.

#16 feat: menambahkan contoh program tahun kabisat
  simple_asm/tahun_kabisat.asm
Labels: enhancement, assembly files, request tim assembly untuk review, HACKTOBERFEST-ACCEPTED

#18 docs: menambahkan template pull request
  .github/pull_request_template.md
Labels: ready-to-merge, documentation, markdown files, HACKTOBERFEST-ACCEPTED

#17 fix typo in line 78 and 98
  README.md
Labels: ready-to-merge, markdown files, HACKTOBERFEST-ACCEPTED

#19 Perpangkatan
  math/math_pangkat.asm
Labels: assembly files, request tim assembly untuk review, HACKTOBERFEST-ACCEPTED

#20 feat: menambahkan contoh program membalikkan kata
  math/perpangkatan.asm
  math/reverse_kata.asm
Labels: enhancement, assembly files, request tim assembly untuk review, HACKTOBERFEST-ACCEPTED

#21 fix typos dan menambah itoa
  ARM64ARCH/sha256.s
  basic/11_perulangan/perulangan.asm
  simple_asm/cekpalindrome.asm
  simple_asm/itoa.asm
Labels: assembly files, request tim assembly untuk review

#22 Khairanabila patch typo docs
  basic/README.md
Labels: markdown files
